name: tests

on:
  push:
    branches:
      - master
      - 1.x
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 7.3, 7.2, 7.1, 7.0]
        # stability: [prefer-lowest, prefer-stable]
        stability: [prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute code sniffer
        run: php vendor/bin/phpcs

      - name: Execute tests
        run: php vendor/bin/phpunit
